---
title: "Schweiz_Unequality"
author: "Branco & Zadeyan"
date: "28 Dezember 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Dieses File dient dem Download sowie der Vorbereitung der Daten um die Ungleichheitsindikatoren für die Schweiz zu berechnen. 
```{r Prepare Data, include=FALSE}

# Download der Daten und Zusammenführen der einzelnen Jahre mit dem pp/dd/hh/rr file.
silc.pp <- tbl(pg, "pp") %>%
  filter(pb020 == "CH") %>%
  select(pb010, pb020, pb030, pb040, pb140, pb150, pb210, pe040, pl060, pl080, pl100, py010g, py050g, px010, px030, py080g, py090g, py100g, py110g, py120g, py130g, py140g) %>%
  collect(n = Inf)
silcp14 <- tbl(pg, "c14p") %>% 
  filter(pb020 == "CH") %>%
  select(pb010, pb020, pb030, pb040, pb140, pb150, pb210,pe040, pl031,pl060, pl080, pl100, 
pl073, pl074, py010g, py050g, px010, px030, py080g, py090g, py100g, py110g, py120g, py130g, py140g) %>%
  collect(n = Inf)
silcp15 <- tbl(pg, "c15p") %>% 
  filter(pb020 == "CH") %>%
  select(pb010, pb020, pb030, pb040, pb140, pb150, pb210,pe040, pl031,pl060, pl080, pl100, 
pl073, pl074, py010g, py050g, px010, px030, py080g, py090g, py100g, py110g, py120g, py130g, py140g) %>%
  collect(n = Inf)
silcp16 <- tbl(pg, "c16p") %>% 
  filter(pb020 == "CH") %>%
  select(pb010, pb020, pb030, pb040, pb140, pb150, pb210,pe040, pl031,pl060, pl080, pl100, 
pl073, pl074, py010g, py050g, px010, px030, py080g, py090g, py100g, py110g, py120g, py130g, py140g) %>%
  collect(n = Inf)
silcp17 <- tbl(pg, "c17p") %>% 
  filter(pb020 == "CH") %>%
  select(pb010, pb020, pb030, pb040, pb140, pb150, pb210,pe040, pl031, pl060, pl080, pl100, 
pl073, pl074, py010g, py050g, px010, px030, py080g, py090g, py100g, py110g, py120g, py130g, py140g) %>%
  collect(n = Inf)
silc.pp <- silc.pp %>% bind_rows(silcp14, silcp15, silcp16, silcp17)
summary(is.na(silc.pp))

silc.hh <- tbl(pg, "hh") %>%
  filter(hb020 == "CH") %>%
  select(hb010, hb020, hb030,hy020, hy110g, hy040g, hy090g, hy050g, hy060g, hy070g, hy080g, hy120g, hy130g, hy140g,hx040, hx050) %>%
  collect(n = Inf)
silch14<- tbl(pg, "c14h") %>%
  filter(hb020 == "CH") %>%
  select(hb010, hb020, hb030, hy020,hy110g, hy040g, hy090g, hy050g, hy060g, hy070g, hy080g, hy120g, hy130g, hy140g,hx040, hx050) %>%
  collect(n = Inf)
silch15<- tbl(pg, "c15h") %>%
  filter(hb020 == "CH") %>%
  select(hb010, hb020, hb030, hy020,hy110g, hy040g, hy090g, hy050g, hy060g, hy070g, hy080g, hy120g, hy130g, hy140g,hx040, hx050) %>%
  collect(n = Inf)
silch16<- tbl(pg, "c16h") %>%
  filter(hb020 == "CH") %>%
  select(hb010, hb020, hb030,hy020, hy110g, hy040g, hy090g, hy050g, hy060g, hy070g, hy080g, hy120g, hy130g, hy140g,hx040, hx050) %>%
  collect(n = Inf)
silch17<- tbl(pg, "c17h") %>%
  filter(hb020 == "CH") %>%
  select(hb010, hb020, hb030, hy020, hy110g, hy040g, hy090g, hy050g, hy060g, hy070g, hy080g, hy120g, hy130g, hy140g,hx040, hx050) %>%
  collect(n = Inf)
silc.hh <- silc.hh %>% bind_rows(silch14, silch15, silch16, silch17)
silc.hh$hy070g[is.na(silc.hh$hy070g)] <- 0
silc.hh$hy120g[is.na(silc.hh$hy120g)] <- 0
summary(is.na(silc.hh))

silc.dd <- tbl(pg, "dd") %>%
  filter(db020 == "CH") %>%
  select(db010, db020, db030, db040, db090) %>%
  collect(n = Inf)
silcd14 <- tbl(pg, "c14d") %>%
  filter(db020 == "CH") %>%
  select(db010, db020, db030, db040, db090) %>%
  collect(n = Inf)
silcd15 <- tbl(pg, "c15d") %>%
  filter(db020 == "CH") %>%
  select(db010, db020, db030, db040, db090) %>%
  collect(n = Inf)
silcd16 <- tbl(pg, "c16d") %>%
  filter(db020 == "CH") %>%
  select(db010, db020, db030, db040, db090) %>%
  collect(n = Inf)
silcd17 <- tbl(pg, "c17d") %>%
  filter(db020 == "CH") %>%
  select(db010, db020, db030, db040, db090) %>%
  collect(n = Inf)
silc.dd <- silc.dd %>% bind_rows(silcd14, silcd15, silcd16, silcd17)
summary(is.na(silc.dd))

silc.rr <- tbl(pg, "rr") %>%
  filter(rb020 == "CH") %>%
  select(rb010, rb020, rb030, rb080, rx030) %>%
  collect(n = Inf)
silcr14 <- tbl(pg, "c14r") %>%
  filter(rb020 == "CH") %>%
  select(rb010, rb020, rb030, rb080, rx030) %>%
  collect(n = Inf)
silcr15 <- tbl(pg, "c15r") %>%
  filter(rb020 == "CH") %>%
  select(rb010, rb020, rb030, rb080, rx030) %>%
  collect(n = Inf)
silcr16 <- tbl(pg, "c16r") %>%
  filter(rb020 == "CH") %>%
  select(rb010, rb020, rb030, rb080, rx030) %>%
  collect(n = Inf)
silcr17 <- tbl(pg, "c17r") %>%
  filter(rb020 == "CH") %>%
  select(rb010, rb020, rb030, rb080, rx030) %>%
  collect(n = Inf)
silc.rr <- silc.rr %>% bind_rows(silcr14, silcr15, silcr16, silcr17)
summary(is.na(silc.rr))



# Erstellen von persönlichen IDs
silc.pp <- silc.pp %>% mutate(personal_id = paste0(pb030, pb010))
silc.rr <- silc.rr %>% mutate(personal_id = paste0(rb030, rb010))


# Zusammenführung von pp und rr
silc.pr <- left_join(silc.pp, silc.rr, 
                     by = c("pb030" = "rb030", "pb010" = "rb010"))

# Zeitreihe für Alter 
silc.pr <- silc.pr %>% 
  mutate(age = pb010 - rb080)
silc.rr <- silc.rr %>% mutate(age=(rb010-rb080))

# Erstellen von Haushalts IDs 
silc.hh <- silc.hh %>% mutate(id_h = paste0(hb030, hb010))
silc.dd <- silc.dd %>% mutate(id_h = paste0(db030, db010))
silc.pr <- silc.pr %>% mutate(id_h = paste0(rx030, pb010))
silc.rr <- silc.rr %>% mutate((id_h = paste0(rx030, rb010)))

# Zusammenführen von pr und h file
silc.prh <- left_join(silc.pr, silc.hh, by = c("id_h"))
# Zusammenführen von prh und d file
silc.dprh <- left_join(silc.prh, silc.dd, by = c("id_h"))
# Persönliche

#Dummy für >= 20 Jahre
silc.dprh <- silc.dprh %>% mutate(grownup=ifelse(age >= 20, 1, 0))

#Datenbereinigung von nicht mehr benötigten Variablen
rm(silcp14, silcp15, silcp16, silcp17,
   silch14, silch15, silch16, silch17,
   silcd14, silcd15, silcd16, silcd17,
   silcr14, silcr15, silcr16, silcr17,
   silc.dd, silc.hh, silc.pp, silc.pr, silc.prh)
silc.dprh <- silc.dprh %>% mutate(personal_id = personal_id.x)
silc.dprh$personal_id.x <- NULL
silc.dprh$personal_id.y <- NULL
colnames(silc.rr) <- c("rb010", "rb020", "rb030", "rb080", "rx030", "personal_id", "age", "id_h")
```

```{r Pre-Tax Factor Income nach P1, include=FALSE}

# Pre-Tax Factor Income berechnen (die Variable py021g wurde ausgelassen da diese für die Schweiz im gesamten Beobachtungszeitraum nur NAs ausweist)
# Auf der Homepage https://www.gesis.org/en/missy/metadata/EU-SILC/2012/Cross-sectional/original#2012-Cross-sectional-PY021G_tab12 kann man die Schweiz bei dieser Variable überhaupt nur in den Jahren 2011 und 2012 auswählen und auch hier sind alle Werte als "missing" eingetragen)

# Summe des persönlichen Einkommens
silc.dprh <- silc.dprh %>% mutate(pip1 = py010g + py050g + py080g)

# Summe des Haushhaltseinkommen
silc.dprh <- silc.dprh %>% group_by(id_h) %>% mutate(sum_pip1 = sum(pip1))

# Äquivalenzeinkommen nach P1
silc.dprh <- silc.dprh %>% 
  mutate(factorincomep1 = ((sum_pip1 + hy110g + hy040g + hy090g) / hx050))
```



```{r Pre-Tax National Income nach P1, include=FALSE}
# Summe des persönlichen Einkommens
silc.dprh <- silc.dprh %>% mutate(pinp1 = pip1 + py090g + py100g)

# Summe des Haushhaltseinkommen
silc.dprh <- silc.dprh %>% group_by(id_h) %>% mutate(sum_pinp1 = sum(pinp1))

# Äquivalenzeinkommen nach P1
silc.dprh <- silc.dprh %>% 
  mutate(nationalincomep1 = ((sum_pinp1 + hy110g + hy040g + hy090g) / hx050))

```

```{r Post-Tax Disposable Income nach P1, include=FALSE}

# Summe des persönlichen Einkommens
silc.dprh <- silc.dprh %>% mutate(pidp1 = pinp1 + py110g + py120g+ py130g+ py140g)

# Summe des Haushhaltseinkommen
silc.dprh <- silc.dprh %>% group_by(id_h) %>% mutate(sum_pidp1 = sum(pidp1))

# Äquivalenzeinkommen nach P1
silc.dprh <- silc.dprh %>% 
  mutate(postaxincomep1 = ((sum_pidp1 + hy110g + hy040g + hy090g + hy050g + hy060g + hy070g + hy080g - hy120g - hy130g - hy140g) / hx050))

#Aufteilung auf alle Personen im Haushalt auch unter 16 Jahren
DatenP1 <- silc.dprh %>% select(id_h, factorincomep1, nationalincomep1, postaxincomep1)
test <- duplicated(DatenP1)  # Datensatz auf Duplikate pr?fen 
is.element(TRUE, test) 
DatenP1 <- DatenP1[which(!duplicated(DatenP1)),]    #doppelt vorhandene haushalte werden gefiltert

DatenP1 <- left_join(silc.rr, DatenP1, by = "id_h")

db <- silc.dprh %>% select(id_h, db040, db090)
db <- db[which(!duplicated(db)),]
DatenP1 <- left_join(DatenP1 , db, by = "id_h")
pb <- silc.dprh %>% select(id_h, pb010)
pb <- pb[which(!duplicated(pb)),]
DatenP1 <- left_join(DatenP1 , pb, by = "id_h")
rm(db, pb, test)

# Entfernen von überflüßigen Variablen
silc.dprh$pip1 <- NULL
silc.dprh$sum_pip1 <- NULL
silc.dprh$pinp1 <- NULL
silc.dprh$sum_pinp1 <- NULL
silc.dprh$pidp1 <- NULL
silc.dprh$sum_pidp1 <- NULL
```


```{r Pre-Tax Factor Income nach P2, include=FALSE}

# Summe des persönlichen Einkommens
silc.dprh <- silc.dprh %>% mutate(pip2 = py010g + py050g + py080g)

# Summe der Haushaltsmitglieder >= 20
silc.dprh <- silc.dprh %>% group_by(id_h) %>% mutate(HM20 = sum(grownup))

# Zuordnung von Einkommen auf Haushaltsebene auf Mitglieder >20Jahre
silc.dprh <- silc.dprh %>% 
  mutate(factorincomep2 = pip2 + (ifelse(age>=20,((hy110g + hy040g + hy090g) / HM20),0)))

```


```{r Pre-Tax National Income nach P2, include=FALSE}

# Um Pre-Tax National Income zu berechnen werden Pensions- und Arbeitslosenzahlungen addiert
silc.dprh <- silc.dprh %>% mutate(nationalincomep2 = factorincomep2 + py090g + py100g)
```


```{r Post-Tax Disposable Income nach P2, include=FALSE}

# Zuordnung von Einkommen auf Haushaltsebene zu Mitglieder >20Jahre
silc.dprh <- silc.dprh %>% mutate(postaxincomep2 = nationalincomep2 + py110g + py120g+ py130g+ py140g+ (ifelse(age>=20, ((hy050g + hy060g + hy070g + hy080g - hy120g - hy130g - hy140g) / HM20),0)))


# Entfernung von nicht mehr benötigten Variablen und Überprüfung von NAs
silc.dprh$pip2 <- NULL

#Filtern >=20 (Nur Personen über 20 Jahre fließen in die Berechnung mit ein)
DatenP2 <- silc.dprh %>% filter(age >= 20)
DatenP2$factorincomep1 <- NULL
DatenP2$nationalincomep1 <- NULL
DatenP2$postaxincomep1 <- NULL
summary(is.na(DatenP2))

```

# ALS NÄCHSTES BITTE FILE 3 INDIKATOREN PRO JAHR AUSFÜHREN
