---
title: "Schweiz Indikatoren"
author: "Branco & Zadeyan"
date: "03 Jänner 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Ungleichheitsindikatoren nach P1, include=FALSE}


#Erstellung des Survey Designs (in Zeile data=(silc.dprh %>% filter(pb010=XX) XX Für bestimmtes Jahr eintragen)
silc.dprh.svy <- svydesign(ids=~id_h,
                       strata=~db040,
                       weights=~db090,
                       data=(silc.dprh)) %>% convey_prep()

# Mittelwert von Factor, National und Post Tax Disposable Income 
MeanIncomeP1 <- c(
  svymean(~factorincomep1,silc.dprh.svy),
  svymean(~nationalincomep1,silc.dprh.svy),
  svymean(~postaxincomep1,silc.dprh.svy))

# Median von Factor, National und Post Tax Disposable Income
MedianIncomeP1 <- c(
  svyquantile(~factorincomep1,silc.dprh.svy,quantile=c(0.5)),
  svyquantile(~nationalincomep1,silc.dprh.svy,quantile=c(0.5)),
  svyquantile(~postaxincomep1,silc.dprh.svy,quantile=c(0.5)))

# Gini von Factor, Natonal und Post Tax Disposable Income
GiniP1 <- c(
  svygini(~factorincomep1, silc.dprh.svy),
  svygini(~nationalincomep1, silc.dprh.svy),
  svygini(~postaxincomep1, silc.dprh.svy))

# P80/P20 von Factor, National und Post Tax Disposable Income
P8020P1 <- c(
  svyqsr(~factorincomep1,silc.dprh.svy),
  svyqsr(~nationalincomep1,silc.dprh.svy),
  svyqsr(~postaxincomep1,silc.dprh.svy))

# Top 10% Anteil von Factor, National und Post Tax Disposable Income

Top10ShareP1 <- c(
svytotal(~factorincomep1,subset(silc.dprh.svy, factorincomep1>=as.numeric(svyquantile(~factorincomep1,silc.dprh.svy,quantile=c(0.9)))))/svytotal(~factorincomep1,silc.dprh.svy),
svytotal(~nationalincomep1,subset(silc.dprh.svy, nationalincomep1>=as.numeric(svyquantile(~nationalincomep1,silc.dprh.svy,quantile=c(0.9)))))/svytotal(~nationalincomep1,silc.dprh.svy),
svytotal(~postaxincomep1,subset(silc.dprh.svy, postaxincomep1>=as.numeric(svyquantile(~postaxincomep1,silc.dprh.svy,quantile=c(0.9)))))/svytotal(~postaxincomep1,silc.dprh.svy))

#Erstellung Tabelle
TabelleP1 <- data.frame(MeanIncomeP1, MedianIncomeP1, GiniP1, P8020P1, Top10ShareP1)
colnames(TabelleP1)<- c("Mean 2008", "Median 2008", "Gini 2008", "P80/20 2008", "Top 10% Share 2008")
```


```{r Ungleichheitsindikatoren nach P2, include=FALSE}

#Filtern >=20
silc.dprhp2 <- silc.dprh %>% filter(age >= 20)

#Erstellung des Survey Designs (in Zeile data=(silc.dprhp2 %>% filter(pb010=XX) XX Für bestimmtes Jahr eintragen)
silc.dprhp2.svy <- svydesign(ids=~id_h,
                       strata=~db040,
                       weights=~db090,
                       data=(silc.dprhp2)) %>% convey_prep()
# Mittelwert von Factor, National und Post Tax Disposable Income 
MeanIncomeP2 <- c(
  svymean(~factorincomep2,silc.dprhp2.svy),
  svymean(~nationalincomep2,silc.dprhp2.svy),
  svymean(~postaxincomep2,silc.dprhp2.svy))

# Median von Factor, National und Post Tax Disposable Income
MedianIncomeP2 <- c(
  svyquantile(~factorincomep2,silc.dprhp2.svy,quantile=c(0.5)),
  svyquantile(~nationalincomep2,silc.dprhp2.svy,quantile=c(0.5)),
  svyquantile(~postaxincomep2,silc.dprhp2.svy,quantile=c(0.5)))

# Gini von Factor, Natonal und Post Tax Disposable Income
GiniP2 <- c(
  svygini(~factorincomep2, silc.dprhp2.svy),
  svygini(~nationalincomep2, silc.dprhp2.svy),
  svygini(~postaxincomep2, silc.dprhp2.svy))

# P80/P20 von Factor, National und Post Tax Disposable Income
P8020P2 <- c(
  svyqsr(~factorincomep2,silc.dprhp2.svy),
  svyqsr(~nationalincomep2,silc.dprhp2.svy),
  svyqsr(~postaxincomep2,silc.dprhp2.svy))

# Top 10% Anteil von Factor, National und Post Tax Disposable Income

Top10ShareP2 <- c(
svytotal(~factorincomep2,subset(silc.dprhp2.svy, factorincomep2>=as.numeric(svyquantile(~factorincomep2,silc.dprhp2.svy,quantile=c(0.9)))))/svytotal(~factorincomep2,silc.dprhp2.svy),
svytotal(~nationalincomep2,subset(silc.dprhp2.svy, nationalincomep2>=as.numeric(svyquantile(~nationalincomep2,silc.dprhp2.svy,quantile=c(0.9)))))/svytotal(~nationalincomep2,silc.dprhp2.svy),
svytotal(~postaxincomep2,subset(silc.dprhp2.svy, postaxincomep2>=as.numeric(svyquantile(~postaxincomep2,silc.dprhp2.svy,quantile=c(0.9)))))/svytotal(~postaxincomep2,silc.dprhp2.svy))

#Erstellung Tabelle
TabelleP2 <- data.frame(MeanIncomeP2, MedianIncomeP2, GiniP2, P8020P2, Top10ShareP2)
colnames(TabelleP2)<- c("Mean 2008", "Median 2008", "Gini 2008", "P80/20 2008", "Top 10% Share 2008")
```
